language: python
python:
  - '3.6'
  - '3.5'

before_script:
  - pip install -r requirements.txt
  
services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="purbeurre.purbeurre.travis_settings"

script:
  - purbeurre/manage.py test
