language: python
python:
  - '3.6'
  - '3.5'

before_script:
  - pip install -r requirements.txt
  
services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="purbeurre.travis_settings", DEBUG_COLLECTSTATIC="1", DISABLE_COLLECTSTATIC="1"

script:
  - purbeurre/manage.py test website
