# Generated by Django 2.2.2 on 2019-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='alternative',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
