# Generated by Django 2.2.2 on 2019-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrigrade',
            field=models.CharField(default='', max_length=1),
        ),
    ]
